name: Build and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'notes/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'notes/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        
      - name: Add Footer To Notes
        run: python add_footer_to_notes.py

      - name: Convert Markdown Docs To HTML
        uses: ldeluigi/markdown-docs@v0.4.2
        with:
          src: notes
          dst: public
          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dsa-ont
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          
