name: Download and update notes

on:
  workflow_dispatch:

jobs:
  update-notes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        
      - name: Download and update notes
        run: python update_notes.py
        env:
          NOTES_ZIP_URL: ${{ secrets.NOTES_ZIP_URL }}
          
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
        
      - name: Add & commit changes
        uses: EndBug/add-and-commit@v7.4.0
        with:
          message: Update notes ${{ steps.current-time.outputs.readableTime }}
